### ISSUE TITLE
Планирование

### ISSUE THREAD

**Issue by DRAMM17** [DRAMM17/LabSix#2]

**Comment by DRAMM17** [comment]
**Определение БД для проекта**

      Система телемаркетинга требует поддержки детально продуманного процесса планирования телефонных звонков, осуществляемых продавцами, оказания помощи в поддержании разговора и фиксирования результатов разговора. 
      Одной из характерных особенностей систем телемаркетинга является сильная зависимость от способности базы данных активно планировать и динамически перепланировать телефонные звонки при поддержке параллельных разговоров

**Comment by alexandrsd** [comment]
Первоначальный вид UML:
![image](https://user-images.githubusercontent.com/56295756/71181580-78266b80-2285-11ea-86c7-2981ff82ef62.png)

**Comment by alexandrsd** [comment]
Финальный вид UML:
![image](https://user-images.githubusercontent.com/56295756/71184597-0d782e80-228b-11ea-9419-c1c2f3b1541b.png)

**Comment by alexandrsd** [comment]
Удовлетворены ли вы UML диаграммой???

**Comment by MagicalDuplex** [comment]
Данная диаграмма полностью описывает, то что нам необходимо, поэтому в дополнении не нуждается.

**Comment by DRAMM17** [comment]
![jeyo1c6PoA8](https://user-images.githubusercontent.com/56295700/71187335-f12ac080-228f-11ea-8a45-4a9dc5e34b3c.jpg)

**Comment by alexandrsd** [comment]
Одобряю
